// Sprint 176 — Create sprint cards module.
// [why] Creates child sprint cards on the board, one per generated sprint,
// with trace links to the originating feature card and spec files.
// Uses direct DB access to create cards — follows the pattern from
// existing board chat assist (createBoardCard).
import { randomUUID } from 'crypto';
import { db } from '../../../../common/db';
import { createGeneratedSprintCard } from '../persistence';
import type { CreateSprintCardsInput, CreateSprintCardsOutput } from '../../types';

export const createSprintCardsDeps = {
  db,
  createGeneratedSprintCard,
};

/**
 * Find the default list/column to place sprint cards in.
 * [why] Looks for a list in the board — prefers a list marked as an
 * execution column, then falls back to the first list on the board.
 */
async function findDefaultList(boardId: string): Promise<string | null> {
  // Try to find a list with 'execution', 'doing', or 'in progress' in the name
  let list = await createSprintCardsDeps
    .db('lists')
    .where({ board_id: boardId })
    .whereRaw('LOWER(title) LIKE ?', ['%sprint%'])
    .select('id')
    .first();

  if (list) return list.id as string;

  list = await createSprintCardsDeps
    .db('lists')
    .where({ board_id: boardId })
    .whereRaw('LOWER(title) LIKE ?', ['%doing%'])
    .select('id')
    .first();

  if (list) return list.id as string;

  // Fall back to first list
  list = await createSprintCardsDeps
    .db('lists')
    .where({ board_id: boardId })
    .orderBy('position', 'asc')
    .select('id')
    .first();

  return list ? (list.id as string) : null;
}

/**
 * Create a sprint card on the board with trace links.
 */
async function createCard({
  title,
  description,
  boardId,
  listId,
  userId,
  traceLinks,
}: {
  title: string;
  description: string;
  boardId: string;
  listId: string;
  userId: string;
  traceLinks: Record<string, unknown>;
}): Promise<{ cardId: string } | null> {
  const cardId = randomUUID();
  const now = new Date().toISOString();

  try {
    // Get the list's position info for card ordering
    const lastCard = await createSprintCardsDeps
      .db('cards')
      .where({ list_id: listId })
      .orderBy('position', 'desc')
      .select('position')
      .first();

    const position = lastCard ? (lastCard.position as number) + 65536 : 65536;

    await createSprintCardsDeps.db('cards').insert({
      id: cardId,
      title,
      description: `${description}\n\n<!-- Generated by Sprint Generation Pipeline -->`,
      board_id: boardId,
      list_id: listId,
      created_by: userId,
      position,
      created_at: now,
      updated_at: now,
    });

    return { cardId };
  } catch (error) {
    console.error(
      `[sprintGeneration/createSprintCards] Failed to create card "${title}":`,
      error instanceof Error ? error.message : String(error)
    );
    return null;
  }
}

/**
 * Create child sprint cards for generated sprint artifacts.
 * One card per sprint, placed in the configured destination list or
 * the default execution column.
 */
export async function createSprintCards({
  cardId,
  workspaceId,
  boardId,
  userId,
  runId,
  artifacts,
  destinationListId,
}: CreateSprintCardsInput): Promise<CreateSprintCardsOutput> {
  // 1. Resolve destination list
  const listId = destinationListId ?? (await findDefaultList(boardId));
  if (!listId) {
    return {
      status: 400,
      name: 'no-destination-list',
      message:
        'No destination list found for sprint cards. Specify destinationListId or ensure the board has lists.',
    };
  }

  const createdCards: Array<{
    sprintCardId: string;
    sprintNumber: number;
    sprintSpecPath: string;
  }> = [];

  const skippedCards: Array<{
    sprintNumber: number;
    reason: string;
  }> = [];

  // 2. Create each sprint card
  for (const artifact of artifacts) {
    const cardTitle = `[Sprint ${artifact.sprintNumber}] ${artifact.title}`;
    const description = [
      `# Sprint ${artifact.sprintNumber}`,
      '',
      `**Spec**: [${artifact.filePath}](${artifact.filePath})`,
      '',
      '## Requirements',
      ...artifact.requirements.map((r, i) => `${i + 1}. ${r}`),
      '',
      '## Acceptance Criteria',
      ...artifact.acceptanceCriteria.map((ac, i) => `${i + 1}. ${ac}`),
      '',
      artifact.dependencies.length > 0
        ? `**Dependencies**: Sprint ${artifact.dependencies.join(', Sprint ')}`
        : '',
    ].join('\n');

    const traceLinks = {
      featureCardId: cardId,
      sprintNumber: artifact.sprintNumber,
      sprintSpecPath: artifact.filePath,
      generationRunId: runId,
    };

    const result = await createCard({
      title: cardTitle,
      description,
      boardId,
      listId,
      userId,
      traceLinks,
    });

    if (result) {
      // Persist the generated sprint card trace record
      await createSprintCardsDeps.createGeneratedSprintCard({
        sprintCardId: result.cardId,
        featureCardId: cardId,
        sprintGenerationRunId: runId,
        sprintNumber: artifact.sprintNumber,
        sprintSpecPath: artifact.filePath,
        traceLinks,
      });

      createdCards.push({
        sprintCardId: result.cardId,
        sprintNumber: artifact.sprintNumber,
        sprintSpecPath: artifact.filePath,
      });
    } else {
      skippedCards.push({
        sprintNumber: artifact.sprintNumber,
        reason: `Failed to create card for sprint ${artifact.sprintNumber}`,
      });
    }
  }

  return {
    status: createdCards.length > 0 ? 201 : 200,
    data: {
      createdCards,
      skippedCards,
    },
  };
}
