// Shared pre-signed GET URL helper for the attachments feature.
// Uses a 1-hour TTL (per Sprint 59 spec) for list-endpoint URLs and thumbnails.
import { GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { s3Client, s3Config } from './config/s3';

/** Default TTL for attachment and thumbnail URLs generated by the list endpoint. */
export const ATTACHMENT_URL_TTL_SECONDS = 60 * 60; // 1 hour

export async function presignGetUrl({
  s3Key,
  ttlSeconds = ATTACHMENT_URL_TTL_SECONDS,
}: {
  s3Key: string;
  ttlSeconds?: number;
}): Promise<{ url: string; expiresAt: string }> {
  const command = new GetObjectCommand({
    Bucket: s3Config.bucket,
    Key: s3Key,
  });

  const url = await getSignedUrl(s3Client, command, { expiresIn: ttlSeconds });
  const expiresAt = new Date(Date.now() + ttlSeconds * 1000).toISOString();

  return { url, expiresAt };
}
