// Orchestrator pipeline — executes the full 5-step pipeline and advances
// the run through the state machine.
// [why] This is the "glue" between the API handler and the individual
// step modules. It executes each step, persists progress, handles retries,
// and transitions the run status.
import { EditRunStatus, EditStepName, MAX_RETRY_ATTEMPTS } from '../../common/config';
import { createEditStep, updateEditStep, updateEditRunStatus } from '../persistence';
import { createFile } from '../fileCreator';
import { editFile } from '../fileEditor';
import { commit } from '../committer';
import type { EditRun, EditStep, PipelineStep, FileScopeEntry } from '../../types';

export const orchestratorDeps = {
  createEditStep,
  updateEditStep,
  updateEditRunStatus,
  createFile,
  editFile,
  commit,
};

/** The pipeline step order with their corresponding run status targets. */
const PIPELINE_ORDER: { step: PipelineStep; nextStatus: EditRunStatus }[] = [
  { step: 'context_gather', nextStatus: EditRunStatus.CONTEXT_GATHERED },
  { step: 'file_scope_plan', nextStatus: EditRunStatus.FILE_SCOPE_PLANNED },
  { step: 'files_create', nextStatus: EditRunStatus.FILES_CREATED },
  { step: 'files_edit', nextStatus: EditRunStatus.FILES_EDITED },
  { step: 'commit', nextStatus: EditRunStatus.COMMITTED },
];

/**
 * Execute a single step in the pipeline.
 * Returns the updated step or an error.
 */
async function executeStep({
  run,
  stepDef,
  contextData,
}: {
  run: EditRun;
  stepDef: { step: PipelineStep; nextStatus: EditRunStatus };
  contextData: {
    intent?: string;
    fileScopePlan?: FileScopeEntry[];
    touchedFiles?: string[];
  };
}): Promise<{ success: boolean; step?: EditStep; error?: string }> {
  // Create or get the step record
  let step = await orchestratorDeps.createEditStep({
    runId: run.id,
    stepName: stepDef.step,
    input: { intent: contextData.intent },
  });

  // Mark as RUNNING
  step = await orchestratorDeps.updateEditStep({
    step,
    status: 'RUNNING' as const,
  });

  try {
    switch (stepDef.step) {
      case 'context_gather': {
        // [why] Context gathering is handled by the aiContext extension
        // via its API. The orchestrator just marks it as complete.
        // The edit handler calls the file-scope planner which already
        // gathers context internally (see Sprint 174 Part 2).
        step = await orchestratorDeps.updateEditStep({
          step,
          status: 'SUCCEEDED' as const,
          output: { gathered: true, source: 'file-scope-pipeline' },
        });
        return { success: true, step };
      }

      case 'file_scope_plan': {
        // [why] File scope plan is already generated by the file-scope
        // endpoint in aiContext. The plan is passed in contextData.
        const plan = contextData.fileScopePlan ?? [];
        step = await orchestratorDeps.updateEditStep({
          step,
          status: 'SUCCEEDED' as const,
          output: { plan, fileCount: plan.length },
        });
        return { success: true, step };
      }

      case 'files_create': {
        const plan = contextData.fileScopePlan ?? [];
        const creates = plan.filter((f) => f.decision === 'create');

        const createdFiles: string[] = [];
        for (const entry of creates) {
          const result = await orchestratorDeps.createFile({
            filePath: entry.filePath,
            content:
              entry.contentHint ??
              `# ${entry.filePath}\n\n<!-- Generated by AI Edit Orchestrator -->\n\n${entry.rationale}`,
          });
          if (result.status >= 400) {
            step = await orchestratorDeps.updateEditStep({
              step,
              status: 'FAILED' as const,
              error: { filePath: entry.filePath, status: result.status, message: result.message },
            });
            return {
              success: false,
              step,
              error: `File creation failed for "${entry.filePath}": ${result.message}`,
            };
          }
          if (result.data?.created) {
            createdFiles.push(entry.filePath);
          }
        }

        step = await orchestratorDeps.updateEditStep({
          step,
          status: 'SUCCEEDED' as const,
          output: { createdFiles, count: createdFiles.length },
        });
        contextData.touchedFiles = [...(contextData.touchedFiles ?? []), ...createdFiles];
        return { success: true, step };
      }

      case 'files_edit': {
        const plan = contextData.fileScopePlan ?? [];
        const edits = plan.filter((f) => f.decision === 'edit');

        const editedFiles: string[] = [];
        for (const entry of edits) {
          const result = await orchestratorDeps.editFile({
            filePath: entry.filePath,
            search: entry.editHint?.snippet ?? '',
            replace:
              entry.contentHint ?? `<!-- Updated by AI Edit Orchestrator -->\n${entry.rationale}`,
            lineRange: entry.editHint?.startLine
              ? { startLine: entry.editHint.startLine, endLine: entry.editHint.endLine }
              : undefined,
          });
          if (result.status >= 400) {
            step = await orchestratorDeps.updateEditStep({
              step,
              status: 'FAILED' as const,
              error: { filePath: entry.filePath, status: result.status, message: result.message },
            });
            return {
              success: false,
              step,
              error: `File edit failed for "${entry.filePath}": ${result.message}`,
            };
          }
          if (result.data?.applied) {
            editedFiles.push(entry.filePath);
          }
        }

        step = await orchestratorDeps.updateEditStep({
          step,
          status: 'SUCCEEDED' as const,
          output: { editedFiles, count: editedFiles.length },
        });
        contextData.touchedFiles = [...(contextData.touchedFiles ?? []), ...editedFiles];
        return { success: true, step };
      }

      case 'commit': {
        const touchedFiles = contextData.touchedFiles ?? [];
        const commitMsg = `feat(ai-edit): ${contextData.intent ?? 'AI edit run'} [${run.card_id}] [REVIEW]`;

        const result = await orchestratorDeps.commit({
          runId: run.id,
          cardId: run.card_id,
          touchedFiles,
          message: commitMsg,
          push: true,
        });

        if (result.status >= 400) {
          step = await orchestratorDeps.updateEditStep({
            step,
            status: 'FAILED' as const,
            error: { status: result.status, message: result.message },
          });
          return { success: false, step, error: `Commit failed: ${result.message}` };
        }

        step = await orchestratorDeps.updateEditStep({
          step,
          status: 'SUCCEEDED' as const,
          output: { commitHash: result.data?.commitHash, files: result.data?.files },
        });
        return { success: true, step };
      }

      default:
        return { success: false, error: `Unknown step: ${stepDef.step}` };
    }
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : 'Unknown error';
    try {
      step = await orchestratorDeps.updateEditStep({
        step,
        status: 'FAILED' as const,
        error: { message: errorMsg },
      });
    } catch {
      // Best effort — if we can't even update the step, just return the error
    }
    return { success: false, step, error: errorMsg };
  }
}

/**
 * Run the full orchestrator pipeline for a given edit run.
 * Executes all 5 steps in order, advancing the run status after each.
 * If any step fails, transitions the run to FAILED.
 *
 * [why] Runs asynchronously — the API returns the run immediately in
 * REQUESTED status and this pipeline runs in the background.
 * The caller can poll GET /ai/edit/:runId to track progress.
 */
export async function runPipeline({
  run,
  intent,
  fileScopePlan,
}: {
  run: EditRun;
  intent: string;
  fileScopePlan?: FileScopeEntry[];
}): Promise<{ success: boolean; run: EditRun; steps: EditStep[]; error?: string }> {
  const contextData: {
    intent: string;
    fileScopePlan?: FileScopeEntry[];
    touchedFiles?: string[];
  } = {
    intent,
    fileScopePlan,
    touchedFiles: [],
  };

  const completedSteps: EditStep[] = [];
  let currentRun = run;

  for (const stepDef of PIPELINE_ORDER) {
    // Advance run status
    const statusResult = await orchestratorDeps.updateEditRunStatus({
      run: currentRun,
      nextStatus: stepDef.nextStatus,
    });

    if (statusResult.status !== 200) {
      return {
        success: false,
        run: currentRun,
        steps: completedSteps,
        error: `Failed to advance run status to ${stepDef.nextStatus}`,
      };
    }

    currentRun = (statusResult as { status: 200; data: { run: EditRun } }).data.run;

    // Execute the step
    const stepResult = await executeStep({
      run: currentRun,
      stepDef,
      contextData,
    });

    if (stepResult.step) {
      completedSteps.push(stepResult.step);
    }

    if (!stepResult.success) {
      // Transition to FAILED
      const failResult = await orchestratorDeps.updateEditRunStatus({
        run: currentRun,
        nextStatus: EditRunStatus.FAILED,
        errorMessage: stepResult.error,
      });

      if ('data' in failResult) {
        currentRun = failResult.data.run;
      }

      return {
        success: false,
        run: currentRun,
        steps: completedSteps,
        error: stepResult.error,
      };
    }

    // Retry handling — if step failed before, check attempt count
    // [why] The UNIQUE constraint on (run_id, step_name) means re-running
    // a step updates the existing row with incremented attempt count.
  }

  return {
    success: true,
    run: currentRun,
    steps: completedSteps,
  };
}
